### PR TITLE
Update workflow files & update Yewprint

### PR DESCRIPTION
**Pull request by yozhgoor**

### CODE REVIEW

**Comment by cecton** [comment]
Maybe we can use a function component at this point xD

Though I think the template should have some useful code to start with so a full fledged component is also useful.

I don't know.... do as you think is best

**Comment by cecton** [comment]
You should also call the auto-detect method at the wasm's entrypoint (lib.rs)

**Comment by yozhgoor** [comment]
> Maybe we can use a function component at this point xD
> 
> Though I think the template should have some useful code to start with so a full fledged component is also useful.
> 
> I don't know.... do as you think is best

Yeah we need to find a balance between being helpful and being annoying. For me the function component in simpler but it doesn't show off what you can do with Yewprint if you want to try it using the template

**Review by cecton — APPROVED** [review]

**Comment by cecton** [comment]
I should have let you merge sorry

**Comment by yozhgoor** [comment]
> I should have let you merge sorry

Don't worry, no problem.

**Pull request merged**
